### ISSUE TITLE
furnace block crash

### ISSUE THREAD

**Issue by fadfhkdfga** [ds58/Panilla#120]
Yes, I'm here again today.

We are a 1.18.2 version creative server where you can import items freely.

/give @p furnace{BlockEntityTag:{RecipesUsed:{"minecraft:bow":1}}} 1

A crash occurs if you break the furnace block obtained by the above method.

Please find the original cause and prevent it!

CRASH LOG:
Description: Exception ticking world

java.lang.ClassCastException: class net.minecraft.world.item.crafting.ShapedRecipes cannot be cast to class net.minecraft.world.item.crafting.RecipeCooking (net.minecraft.world.item.crafting.ShapedRecipes and net.minecraft.world.item.crafting.RecipeCooking are in unnamed module of loader java.net.URLClassLoader @6bf2d08e)
	at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.lambda$getRecipesToAwardAndPopExperience$1(AbstractFurnaceBlockEntity.java:626)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.getRecipesToAwardAndPopExperience(AbstractFurnaceBlockEntity.java:624)
	at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.getRecipesToAwardAndPopExperience(AbstractFurnaceBlockEntity.java:613)
	at net.minecraft.world.level.block.AbstractFurnaceBlock.onRemove(AbstractFurnaceBlock.java:73)
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.onRemove(BlockBehaviour.java:1011)
	at net.minecraft.world.level.chunk.LevelChunk.setBlockState(LevelChunk.java:587)
	at net.minecraft.world.level.Level.setBlock(Level.java:537)
	at net.minecraft.world.level.Level.setBlock(Level.java:499)
	at net.minecraft.world.level.Level.removeBlock(Level.java:663)
	at net.minecraft.world.level.block.piston.PistonBaseBlock.triggerEvent(PistonBaseBlock.java:278)
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.triggerEvent(BlockBehaviour.java:969)
	at net.minecraft.server.level.ServerLevel.doBlockEvent(ServerLevel.java:1689)
	at net.minecraft.server.level.ServerLevel.runBlockEvents(ServerLevel.java:1675)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:633)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1593)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.lambda$getRecipesToAwardAndPopExperience$1(AbstractFurnaceBlockEntity.java:626)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.getRecipesToAwardAndPopExperience(AbstractFurnaceBlockEntity.java:624)
	at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.getRecipesToAwardAndPopExperience(AbstractFurnaceBlockEntity.java:613)
	at net.minecraft.world.level.block.AbstractFurnaceBlock.onRemove(AbstractFurnaceBlock.java:73)
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.onRemove(BlockBehaviour.java:1011)
	at net.minecraft.world.level.chunk.LevelChunk.setBlockState(LevelChunk.java:587)
	at net.minecraft.world.level.Level.setBlock(Level.java:537)
	at net.minecraft.world.level.Level.setBlock(Level.java:499)
	at net.minecraft.world.level.Level.removeBlock(Level.java:663)
	at net.minecraft.world.level.block.piston.PistonBaseBlock.triggerEvent(PistonBaseBlock.java:278)
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.triggerEvent(BlockBehaviour.java:969)
	at net.minecraft.server.level.ServerLevel.doBlockEvent(ServerLevel.java:1689)
	at net.minecraft.server.level.ServerLevel.runBlockEvents(ServerLevel.java:1675)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:633)

USER CRASH LOG:
[19:11:43] [Server thread/ERROR]: Error whilst processing packet net.minecraft.network.protocol.game.PacketPlayInBlockDig@55aa3dc3 for Anonympus[/0.0.0.0:52738]
java.lang.ClassCastException: class net.minecraft.world.item.crafting.ShapedRecipes cannot be cast to class net.minecraft.world.item.crafting.RecipeCooking (net.minecraft.world.item.crafting.ShapedRecipes and net.minecraft.world.item.crafting.RecipeCooking are in unnamed module of loader java.net.URLClassLoader @6bf2d08e)
	at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.lambda$getRecipesToAwardAndPopExperience$1(AbstractFurnaceBlockEntity.java:626) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.getRecipesToAwardAndPopExperience(AbstractFurnaceBlockEntity.java:624) ~[?:?]
	at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.getRecipesToAwardAndPopExperience(AbstractFurnaceBlockEntity.java:613) ~[?:?]
	at net.minecraft.world.level.block.AbstractFurnaceBlock.onRemove(AbstractFurnaceBlock.java:73) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.onRemove(BlockBehaviour.java:1011) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk.setBlockState(LevelChunk.java:587) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:537) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:499) ~[?:?]
	at net.minecraft.world.level.Level.removeBlock(Level.java:663) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:455) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:366) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:248) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1770) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:14) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:11:43] [Server thread/WARN]: Block entity minecraft:furnace @ BlockPosition{x=4252397, y=0, z=-1450073} state Block{minecraft:air} invalid for ticking:
[19:11:43] [Server thread/INFO]: Anonymous lost connection: Packet processing error

SERVER OFF LOG:
[19:12:34] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1612) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.world.item.crafting.ShapedRecipes cannot be cast to class net.minecraft.world.item.crafting.RecipeCooking (net.minecraft.world.item.crafting.ShapedRecipes and net.minecraft.world.item.crafting.RecipeCooking are in unnamed module of loader java.net.URLClassLoader @6bf2d08e)
	at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.lambda$getRecipesToAwardAndPopExperience$1(AbstractFurnaceBlockEntity.java:626) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.getRecipesToAwardAndPopExperience(AbstractFurnaceBlockEntity.java:624) ~[?:?]
	at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.getRecipesToAwardAndPopExperience(AbstractFurnaceBlockEntity.java:613) ~[?:?]
	at net.minecraft.world.level.block.AbstractFurnaceBlock.onRemove(AbstractFurnaceBlock.java:73) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.onRemove(BlockBehaviour.java:1011) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk.setBlockState(LevelChunk.java:587) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:537) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:499) ~[?:?]
	at net.minecraft.world.level.Level.removeBlock(Level.java:663) ~[?:?]
	at net.minecraft.world.level.block.piston.PistonBaseBlock.triggerEvent(PistonBaseBlock.java:278) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.triggerEvent(BlockBehaviour.java:969) ~[?:?]
	at net.minecraft.server.level.ServerLevel.doBlockEvent(ServerLevel.java:1689) ~[?:?]
	at net.minecraft.server.level.ServerLevel.runBlockEvents(ServerLevel.java:1675) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:633) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1593) ~[paper-1.18.2.jar:git-Paper-388]
	... 5 more
[19:12:34] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.ClassCastException: class net.minecraft.world.item.crafting.ShapedRecipes cannot be cast to class net.minecraft.world.item.crafting.RecipeCooking (net.minecraft.world.item.crafting.ShapedRecipes and net.minecraft.world.item.crafting.RecipeCooking are in unnamed module of loader java.net.URLClassLoader @6bf2d08e)
	at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.lambda$getRecipesToAwardAndPopExperience$1(AbstractFurnaceBlockEntity.java:626) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.getRecipesToAwardAndPopExperience(AbstractFurnaceBlockEntity.java:624) ~[?:?]
	at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.getRecipesToAwardAndPopExperience(AbstractFurnaceBlockEntity.java:613) ~[?:?]
	at net.minecraft.world.level.block.AbstractFurnaceBlock.onRemove(AbstractFurnaceBlock.java:73) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.onRemove(BlockBehaviour.java:1011) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk.setBlockState(LevelChunk.java:587) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:537) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:499) ~[?:?]
	at net.minecraft.world.level.Level.removeBlock(Level.java:663) ~[?:?]
	at net.minecraft.world.level.block.piston.PistonBaseBlock.triggerEvent(PistonBaseBlock.java:278) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.triggerEvent(BlockBehaviour.java:969) ~[?:?]
	at net.minecraft.server.level.ServerLevel.doBlockEvent(ServerLevel.java:1689) ~[?:?]
	at net.minecraft.server.level.ServerLevel.runBlockEvents(ServerLevel.java:1675) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:633) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1593) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by ds58** [comment]
Thanks. New release `1.8.3` out on SpigotMC which fixes this.
