### ISSUE TITLE
Server startup error

### ISSUE THREAD

**Issue by Apexo01** [ds58/Panilla#127]
```bash
[18:35:59] [ServerMain/ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins\panilla-craftbukkit-v1_19_R3-1.9.0.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins\panilla-craftbukkit-v1_19_R3-1.9.0.jar' failed to load!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.server.Main.main(Main.java:126) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at org.bukkit.craftbukkit.Main.main(Main.java:323) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Directory 'plugins\panilla-craftbukkit-v1_19_R3-1.9.0.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:54) ~[purpur-1.19.4.jar:git-Purpur-1976]
	... 20 more
```

I removed from the list all the versions that I do not need. When I run it, it gives an error that there are no configs. Maybe I took the wrong build, I took the jar from craftbukkit 1_19_R3/build/libs/(filename)

**Comment by Apexo01** [comment]
![image](https://github.com/ds58/Panilla/assets/63789651/e5ac2ea2-b36a-4331-9857-fb898f802873)

**Comment by Apexo01** [comment]
Oh, thank you. I should write about it in the Readme to help others like me.
