### ISSUE TITLE
Crash on Paper 1.20.6

### ISSUE THREAD

**Issue by james090500** [ds58/Panilla#147]
```
paper version
[17:19:00 INFO]: Checking version, please wait...
[17:19:00 INFO]: This server is running Paper version 1.20.6-130-master@5d8e53d (2024-06-01T14:32:53Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-496 (MC: 1.20.4)
```

```
[17:15:44 ERROR]: Error occurred while enabling Panilla v1.11.3 (Is it up to date?)
java.lang.StringIndexOutOfBoundsException: Range [23, 22) out of bounds for length 22
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) ~[?:?]
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865) ~[?:?]
        at java.base/java.lang.String.substring(String.java:2834) ~[?:?]
        at java.base/java.lang.String.substring(String.java:2807) ~[?:?]
        at Panilla.jar/com.ruinscraft.panilla.bukkit.PanillaPlugin.onEnable(PanillaPlugin.java:136) ~[Panilla.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by minoneer** [comment]
I second this issue - we observe the same issue on Paper 1.20.6. It is likely due to the removal of the internal package relocations (e.g., "V1_20_R4"). Refer to this announcement: https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/

**Comment by Nielsbest** [comment]
I triple this issue, same as the gentlemen above.

**Comment by ds58** [comment]
1.20.6 and 1.21/1.21.1 are now supported on **Paper** in the latest release.
