### ISSUE TITLE
Panilla Plugin Prevents Players from Joining Paper 1.21 Server

### ISSUE THREAD

**Issue by LBxrman** [ds58/Panilla#153]
![image](https://github.com/user-attachments/assets/f5c85808-2177-4888-9542-311907216597)
**I tried the latest release of the Panilla plugin on a Paper 1.21 server, but players were unable to join, and there was a bunch of errors:**
[08:35:03 INFO]: Elwc_awa[/27.187.92.169:52945] logged in with entity id 4 at ([world]72.89713232556464, -51.51427071378095, -9.456234292667068)
[08:35:03 ERROR]: Thread Netty Server IO #1 failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2384) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerLevel.getEntity(ServerLevel.java:1920) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at Panilla.jar/com.ruinscraft.panilla.paper.v1_21.io.PacketInspector.checkPacketPlayOutSpawnEntity(PacketInspector.java:136) ~[Panilla.jar:?]
        at Panilla.jar/com.ruinscraft.panilla.api.io.IPacketInspector.checkPlayOut(IPacketInspector.java:71) ~[Panilla.jar:?]
        at Panilla.jar/com.ruinscraft.panilla.api.io.dplx.PacketInspectorDplx.write(PacketInspectorDplx.java:41) ~[Panilla.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:513) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49) ~[ProtocolLib.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[08:35:03 ERROR]: Thread Netty Server IO #1 failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2384) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerLevel.getEntity(ServerLevel.java:1920) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at Panilla.jar/com.ruinscraft.panilla.paper.v1_21.io.PacketInspector.checkPacketPlayOutSpawnEntity(PacketInspector.java:136) ~[Panilla.jar:?]
        at Panilla.jar/com.ruinscraft.panilla.api.io.IPacketInspector.checkPlayOut(IPacketInspector.java:71) ~[Panilla.jar:?]
        at Panilla.jar/com.ruinscraft.panilla.api.io.dplx.PacketInspectorDplx.write(PacketInspectorDplx.java:41) ~[Panilla.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:513) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49) ~[ProtocolLib.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[08:35:03 INFO]: Elwc_awa lost connection: Internal Exception: java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
[08:35:03 INFO]: Elwc_awa left the game

**Comment by LBxrman** [comment]
Possible Conflict with ProtocolLib Plugin?

**Comment by ds58** [comment]
Thanks. Working on a fix.

**Comment by ds58** [comment]
New release `1.12.1` out which fixes the issue.
