### ISSUE TITLE
[emergency] This error occurs when you first use the book.

### ISSUE THREAD

**Issue by fadfhkdfga** [ds58/Panilla#157]
Could not pass event PlayerJoinEvent to Panilla v1.12.1
java.lang.ClassCastException: class com.ruinscraft.panilla.lib.nbtapi.NBTListCompound cannot be cast to class java.lang.String (com.ruinscraft.panilla.lib.nbtapi.NBTListCompound is in unnamed module of loader 'Panilla-1.12.1.jar' @706ff79; java.lang.String is in module java.base of loader 'bootstrap')
	at Panilla-1.12.1.jar/com.ruinscraft.panilla.paper.v1_21.nbt.NbtTagList.getString(NbtTagList.java:23) ~[Panilla-1.12.1.jar:?]
	at Panilla-1.12.1.jar/com.ruinscraft.panilla.api.nbt.checks.paper1_20_6.NbtCheck_WritableBookContent.check(NbtCheck_WritableBookContent.java:53) ~[Panilla-1.12.1.jar:?]
	at Panilla-1.12.1.jar/com.ruinscraft.panilla.api.nbt.checks.NbtChecks.checkAll(NbtChecks.java:172) ~[Panilla-1.12.1.jar:?]
	at Panilla-1.12.1.jar/com.ruinscraft.panilla.paper.v1_21.InventoryCleaner.clean(InventoryCleaner.java:42) ~[Panilla-1.12.1.jar:?]
	at Panilla-1.12.1.jar/com.ruinscraft.panilla.bukkit.JoinQuitListener.onJoin(JoinQuitListener.java:31) ~[Panilla-1.12.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor259.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-13-7c9240f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]t

**Comment by fadfhkdfga** [comment]
+ If another player picks up a book item that has fallen on the ground, they will be kicked due to this error.
![image](https://github.com/user-attachments/assets/5ac661b7-f804-4fd7-ac9c-89677ca43cb9)

**Comment by ds58** [comment]
Fixed in release `1.12.2`, thanks for reporting
